#!/usr/bin/env python

import os, sys
import json
import interactions as i

def string_to_symbol(s):
  try:
    return globals()[s]
  except:
    return False

def load_json_comp(path):
    file = open(path)
    try:
        fstr = file.read()
        res = json.loads(fstr)
        file.close()
        return res
    except:
        file.close()
        raise

def compstruct(d):
    res = {}
    for k in d:
        ksym = string_to_symbol(k)
        if ksym:
            res[k] = ksym(d[k])
        else:
            res[k] = d[k]
    return res


def living(d):
    d['hp'] = d['hpmax']
    return d

def load_editables():
    pathname = os.path.dirname(sys.argv[0]) + "edit"
    for subdir, dirs, files in os.walk(pathname):
        for file in files:
            print file
            print file.split(".")[-1:]




def Main():
    parsed = load_json_comp("edit/mouse.json")
    print parsed
    res = compstruct(parsed)
    print res
    print i.name(res)
    print i.plural_name(res)
    print i.description(res)
    load_editables()

if __name__ == "__main__" :Main()




